[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
extend-select = [
  'D',  # pydocstyle
  'E', 'W',  # pycodestyle
  'F',  # pyflakes
  'I',  # sort imports
  'UP',  # pyupgrade
  'RUF',  # ruff's own rules
  'SIM',  # pyflakes simplicity
  'C90',  # additional complexity rules
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
combine-as-imports = true
split-on-trailing-comma = false

